apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kite.fullname" . }}-secret
  labels:
    {{- include "kite.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.jwtSecret | b64enc | quote }}
  KITE_ENCRYPT_KEY: {{ .Values.encryptKey | b64enc | quote }}
  {{- if .Values.host }}
  HOST: {{ .Values.host | b64enc | quote }}
  {{- end }}
  {{- if .Values.webhook.enabled }}
  WEBHOOK_USERNAME: {{ .Values.webhook.username | b64enc | quote }}
  WEBHOOK_PASSWORD: {{ .Values.webhook.password | b64enc | quote }}
  {{- end }}
  DB_TYPE: {{ .Values.db.type | b64enc | quote }}
  {{- if eq .Values.db.type "sqlite" }}
  DB_DSN: {{ (printf "%s/%s" .Values.db.sqlite.persistence.mountPath .Values.db.sqlite.persistence.filename) | b64enc | quote }}
  {{- else }}
  DB_DSN: {{ .Values.db.dsn | b64enc | quote }}
  {{- end }}